export default {
    add         : require('./icons/add.svg'),
    back        : require('./icons/back.svg'),
    close       : require('./icons/close.svg'),
    delete      : require('./icons/delete.svg'),
    done        : require('./icons/done.svg'),
    edit        : require('./icons/edit.svg'),
    menu        : require('./icons/menu.svg'),
    recover     : require('./icons/recover.svg'),
    search      : require('./icons/search.svg'),
    share       : require('./icons/share.svg'),
    contentHide : require('./icons/eye-close.svg'),
    contentShow : require('./icons/eye-open.svg'),
    copy        : require('./icons/copy.svg'),
}
